import AsymptoticStatistics.Core.EIF
import AsymptoticStatistics.ForMathlib.CondExpL2
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2
import Mathlib.MeasureTheory.Measure.Map

/-!
# Information-loss operator

vdV §25.6 (observed-data scores and Coarsening At Random). The observed score
is the conditional expectation of the full-data score under the σ-algebra
`M⁻¹(σ_obs)` generated by the coarsening map `M : Ω_full → Ω_obs` (lem:25.34).

This file works with two probability measures: `P_full` on `Ω_full` and
`P_obs := P_full.map M` on `Ω_obs`. The information-loss operator bridges
`↥(L²₀(P_full)) →L[ℝ] ↥(L²₀(P_obs))` via `condExpL2` plus the Doob L²
isomorphism `doobL2Equiv`. Downstream theorems (lem:25.34, thm:25.40,
lem:25.41, cor:25.42) reference the operator and the Doob equivalence's
defining identity `doobL2Equiv_comp_apply` by name.
-/

open MeasureTheory Filter Topology
open scoped InnerProductSpace ENNReal

set_option linter.dupNamespace false

namespace AsymptoticStatistics.Operators.InformationLoss

open AsymptoticStatistics.Core.Hilbert
open AsymptoticStatistics.ForMathlib.CondExpL2

variable {Ω_full Ω_obs : Type*}
  [MeasurableSpace Ω_full] [MeasurableSpace Ω_obs]
end AsymptoticStatistics.Operators.InformationLoss
